CREATE CONSTRAINT mpgnode_id IF NOT EXISTS
FOR (n:MPGNode) REQUIRE n.id IS UNIQUE;

CREATE CONSTRAINT segment_id IF NOT EXISTS
FOR (s:Segment) REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT evidence_id IF NOT EXISTS
FOR (e:Evidence) REQUIRE e.id IS UNIQUE;

CREATE INDEX mpgnode_level IF NOT EXISTS
FOR (n:MPGNode) ON (n.level);
